stages:
- build-and-push

variables:
  IMAGE_TAG: "390.0.0"

build:
  stage: build-and-push
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  only:
  - main
  services:
    - docker:dind
  before_script:
  - echo "${DOCKER_CREDS}" | docker login --username mosstech --password-stdin
  script:
    - docker build -t mosstech/gcloud-and-docker:${IMAGE_TAG} .
    - docker push mosstech/gcloud-and-docker:${IMAGE_TAG}
