stages:
- build-and-push

variables:
  IMAGE_TAG: "512.0.0"

build:
  stage: build-and-push
  image: docker:stable
  only:
  - main
  services:
    - docker:dind
  before_script:
  - until docker info >/dev/null; do sleep 1; echo "Waiting for docker startup"; done
  - echo "${DOCKER_CREDS}" | docker login --username al3xos --password-stdin
  script:
    - docker build -t al3xos/gcloud-and-docker:${IMAGE_TAG} .
    - docker push al3xos/gcloud-and-docker:${IMAGE_TAG}
